# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5176dcbef91511a8ae645fe30c57e76dc375c0ea6f9ae3a8c51c5089f3cec365748c41c67680fd1174c74614b5db3eeea34251f6ada60d1898ad0ac1f3141e68

test:
  secret_key_base: 7153bcd75c29ee161575203ad67640af7da6d2ea4e60ccf7bf8afc02e5f4cb9acc20c7e3919158f979e6fbb2e6b3d8c7c49b0b39c3ee0e011e45f1321938723d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
